### ISSUE TITLE
Psi4 Tests

### ISSUE THREAD

**Issue by sheepforce** [kratman/FLUKE_QMMM#18]
Hi,
all tests with Psi4 fail and having a look at `tests.out` (after commenting out `CleanFiles()` in `runtests`) tells me

    Traceback (most recent call last):
      File "/cluster/software/psi4/1.1/bin/psi4", line 186, in <module> 
        psi4.core.set_num_threads(int(args["nthread"]), quiet=True)
    ValueError: invalid literal for int() with base 10: '16-i'
    Warning: SCF did not converge!!!

Nevertheless, Psi4 passes its own test suite and runs the Lichem generated input fine, when called manually, so i suspect the error to be somewhere else.

**Comment by kratman** [comment]
I am looking into it now. Thank you for the report

**Comment by kratman** [comment]
Confirmed and fixed. Let me know if you have other issues
