### ISSUE TITLE
link PSI4 and TINKER

### ISSUE THREAD

**Issue by Wodnerstruck** [kratman/FLUKE_QMMM#21]
Hi! I moved the -static keyword in Makefile ,then install LICHEM(because there's no static lib in our cluster )
Then I run ./runtests Ncpus psi4 tinker ,it's ok。
But when I run some test in /tests/PSI4_TINKER(eg. water-dimer), a problem  occurred：

LICHEM can only call Psi4 or TINKER separately to complete QM and MM calculations, respectively.Once the QM/MM calculation is performed, Psi4 will immediately report an error saying that SCF does not converge ,and the QM energy value is so large . It appears that no SCF iteration has been performed at all，I wonder what happened，thanks!

**Comment by kratman** [comment]
Which versions of PSI4 and TINKER are you using? I have not worked on this project in a couple years since moving out of academia, so I suspect that my code might not handle newer versions of the QM and MM packages.

Also as a side question, in your "./runtests Ncpus psi4 tinker" how many CPUs did you use? Seems odd that you say the tests run OK but then you running the water dimer from the test folder fails. Can you add more details?

**Comment by g-andres** [comment]
Hi,
Please check: https://github.com/CisnerosResearch/LICHEM, that is the repo with the latest version.

**Comment by Wodnerstruck** [comment]
> Which versions of PSI4 and TINKER are you using? I have not worked on this project in a couple years since moving out of academia, so I suspect that my code might not handle newer versions of the QM and MM packages.
> 
> Also as a side question, in your "./runtests Ncpus psi4 tinker" how many CPUs did you use? Seems odd that you say the tests run OK but then you running the water dimer from the test folder fails. Can you add more details?

I'm sorry, I rerun the ./runtest and failed，I mistakenly thought it was running successfully.
PSI4 version -1.6.1 ,Tinker version -8.10.2 ,in my  "./runtests Ncpus psi4 tinker",I used 10 CPUs
I checked LICHEM repo I have cloned ,it's the latest version, but I post issue to the older repo , I'm so sorry.

**Comment by kratman** [comment]
No worries, this was the original repo that was cited. This version just became unused after I finished my post-doc.

This version was not really used with some of the newer QM and MM packages, so the compatibility is hit or miss. The other repo mentioned above has been updated more recently.

**Comment by Wodnerstruck** [comment]
> Hi,
> Please check: https://github.com/CisnerosResearch/LICHEM, that is the repo with the latest version.

Thanks! Actually I have installed the latest version, but the The runtest procedure will still fail（Psi4 -1.6.1 Tinker -8.10.2)
Then I run command line as "lichem -n Ncpus -x xyzfile.xyz -c confile.inp -r regfile.inp -o output.xyz",it's OK when running QM  calculation or MM calculation, but failed when running QM/MM calculations:

Warning: SCF did not converge!!!
 LICHEM will attempt to continue...

and in log file:
Single-point energy:
 46 
 47   QM energy: 1000000000000000 a.u.
 48   MM energy: 0.00362944969260 a.u.
 49   QMMM energy: 1000000000000000 a.u. | 6275094746845428 kcal


(PS: I renamed the key file corresponding to the regfile to “tinker.key” , otherwise it will prompt me that can't find “tinker.key”)

**Comment by g-andres** [comment]
please try the latest runtests script (available in the src directory) also at:  
https://github.com/emleddin/LICHEM/blob/main/src/runtests.py
it still has a couple of bugs we are fixing (for the frequency calculation, which fails, and for QSM, which should not be tested yet), you can skip the QSM test by hitting ctrl-C and selecting "skip this test"

**Comment by Wodnerstruck** [comment]
> please try the latest runtests script (available in the src directory) also at:
> https://github.com/emleddin/LICHEM/blob/main/src/runtests.py
> it still has a couple of bugs we are fixing (for the frequency calculation, which fails, and for QSM, which should not be tested yet), you can skip the QSM test by hitting ctrl-C and selecting "skip this test"

Running runtest.py also continues to fail，and QM/MM calculations are not performed correctly by using command line "lichem" .

Is it necessary to include the -static keyword in the Makefile when compiling?

**Comment by kratman** [comment]
It should not be necessary to compile statically, that was just convenient for putting it onto clusters since LICHEM itself was quite simple. The static build has nothing to do with the PSI4 or TINKER.

I still suspect that it is a problem with the versions, but can you post the PSI4, TINKER, and LICHEM output files for one of the tests? There is a setting to make sure the files are kept if you cannot find them.

**Comment by g-andres** [comment]
I agree with previous comment by @kratman, just for completeness, I would suggest to try a fresh clone of the repo with the latest version, and configure/compile as is, followed by testing with the runtests.py script.

You can also send me any files (inputs/outputs) for the tests that are having issues to: andres@utdallas.edu

Thanks

**Comment by kratman** [comment]
@Wodnerstruck Can this ticket be closed? Did you get any of the versions working?

**Comment by kratman** [comment]
Since there was no response. I am going to close this as resolved.
